apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: aicd-dev
type: Opaque
data:
  minio-access-key: bWluaW8=  # base64 encoded "minio"
  minio-secret-key: bWluaW9zZWNyZXQ=  # base64 encoded "minosecret"