apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: aicd-dev
type: Opaque
data:
  postgresql-password: YWljZFVzZXI=  # base64 encoded "aicdUser"
  postgresql-root-password: YWljZFJvb3Q=  # base64 encoded "aicdRoot"